### ISSUE TITLE
Igel 2.2.0 segmentation fault on Raspberry Pi 3b+

### ISSUE THREAD

**Issue by ScallyBag** [vshcherbyna/igel#131]
Hi Volodymyr,

After updating to Igel v2.2.0 on GitHub I ran cmake.. and Make and compiled Igel 2.2.0, however on startup and trying go infinite, I get a segmentation fault as attached:

Al@PicoChess:~/igel/src $ cmake ..
-- The C compiler identification is GNU 6.3.0
-- The CXX compiler identification is GNU 6.3.0
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
CMake Warning (dev) in CMakeLists.txt:
  No cmake_minimum_required command is present.  A line of code such as

    cmake_minimum_required(VERSION 3.13)

  should be added at the top of the file.  The version specified may be lower
  if you wish to support older CMake versions for this project.  For more
  information run "cmake --help-policy CMP0000".
This warning is for project developers.  Use -Wno-dev to suppress it.

-- Configuring done
-- Generating done
-- Build files have been written to: /home/Al/igel/src
Al@PicoChess:~/igel/src $ make clean
Al@PicoChess:~/igel/src $ make -j4
Scanning dependencies of target igel
[ 11%] Building CXX object CMakeFiles/igel.dir/eval.o
[ 11%] Building CXX object CMakeFiles/igel.dir/bitboards.o
[ 16%] Building CXX object CMakeFiles/igel.dir/eval_params.o
[ 22%] Building CXX object CMakeFiles/igel.dir/history.o
[ 27%] Building CXX object CMakeFiles/igel.dir/main.o
[ 33%] Building CXX object CMakeFiles/igel.dir/moveeval.o
[ 38%] Building CXX object CMakeFiles/igel.dir/moves.o
[ 44%] Building CXX object CMakeFiles/igel.dir/notation.o
[ 50%] Building CXX object CMakeFiles/igel.dir/position.o
[ 55%] Building CXX object CMakeFiles/igel.dir/search.o
[ 61%] Building CXX object CMakeFiles/igel.dir/texel.o
[ 66%] Building CXX object CMakeFiles/igel.dir/time.o
[ 72%] Building CXX object CMakeFiles/igel.dir/tt.o
[ 77%] Building CXX object CMakeFiles/igel.dir/uci.o
[ 83%] Building CXX object CMakeFiles/igel.dir/utils.o
[ 88%] Building C object CMakeFiles/igel.dir/fathom/tbcore.o
[ 94%] Building C object CMakeFiles/igel.dir/fathom/tbprobe.o
[100%] Linking CXX executable igel
[100%] Built target igel

Al@PicoChess:~/igel/src $ ./igel
Igel 2.2.0 by V. Medvedev, V. Shcherbyna
uci
id name Igel 2.2.0
id author V. Medvedev, V. Shcherbyna
option name Hash type spin default 128 min 1 max 1048576
option name Threads type spin default 1 min 1 max 1024
option name SyzygyPath type string default <empty>
option name SyzygyProbeDepth type spin default 1 min 1 max 128
option name Ponder type check default false
option name Level type spin default 20 min 0 max 20
uciok
go infinite
Segmentation fault
Al@PicoChess:~/igel/src $

Thanks,

Al on Picochess.

**Comment by ScallyBag** [comment]
By the way I’m using cmake 3.13.1

Al@PicoChess:~ $ cmake --version
cmake version 3.13.1

Al.

**Comment by vshcherbyna** [comment]
Hey @ScallyBag ,

Did you use the build provided in the package by me or it was your compile? Can you please run my compile to validate it? I may have an idea of why this is happening.

**Comment by ScallyBag** [comment]
It’s my compile as provided. You haven’t supplied a Raspberry Pi Compile for your latest version. 

Al.

**Comment by vshcherbyna** [comment]
I did :) Please re-check the archive, it was added a bit later.

**Comment by vshcherbyna** [comment]
As per my message in http://talkchess.com/forum3/viewtopic.php?p=823269&sid=cee0ef4c6f9ad236dfb2a96dfa62c124#p823269 at the bottom I mention that the usual compiles will be provided a bit later, this part is done in the morning today.

**Comment by ScallyBag** [comment]
Sorry, I can’t see them.

3 assets, 2 source and only 1 compile for windows.

**Comment by vshcherbyna** [comment]
Hey Scally,

Sorry if I was not specific. I mean that inside the zip archive at https://github.com/vshcherbyna/igel/releases/download/2.2.0/igel-2.2.0.bin.zip you have multiple files inside, there is a folder "raspberryPi" inside that contains file "igel".

Once you confirm that it works I will make a change to master because I may know what the problem is, so once confirmed I will proceed with the change.

**Comment by ScallyBag** [comment]
Hi Volodymyr,

Your compile works, what did you do differently?

Al.

**Comment by vshcherbyna** [comment]
Hey @ScallyBag ,

Thanks for confirming that it works. The problem is caused by a use of hardware instructions that are not implemented in raspberry architecture. I just did a pull request to fix that.
