### ISSUE TITLE
Problems compiling Igel 2.5.0 on RPi.

### ISSUE THREAD

**Issue by ScallyBag** [vshcherbyna/igel#173]
Hi Volodymyr,

I’m having problems compiling your latest release for Picochess:

uci.cpp: In member function ‘int Uci::handleCommands()’:
uci.cpp:63:40: error: ‘ARCHITECTURE’ was not declared in this scope
     std::cout << "Igel " << VERSION << ARCHITECTURE << " by V. Medvedev, V. Shcherbyna" << std::endl;
                                        ^~~~~~~~~~~~
uci.cpp: In member function ‘void Uci::onUci()’:
uci.cpp:109:48: error: ‘ARCHITECTURE’ was not declared in this scope
     std::cout << "id name Igel " << VERSION << ARCHITECTURE << std::endl;
                                                ^~~~~~~~~~~~
makefile:22: recipe for target 'basic' failed
make: *** [basic] Error 1
Al@PicoStretch:~/igel/src $

Thanks,

Al.

**Comment by ScallyBag** [comment]
Update,

I can compile it and it runs fine, by removing the 2 instances of  “<< ARCHITECTURE <<“ from uci.cpp

Al.

**Comment by vshcherbyna** [comment]
Great to hear you are unblocked Scally, I'll see for next release how to address the RPi compile.

**Comment by vshcherbyna** [comment]
Fixed as of Igel 2.6.0 https://github.com/vshcherbyna/igel/releases/tag/2.6.0
