### ISSUE TITLE
Issue with Android compiling

### ISSUE THREAD

**Issue by AlexB123** [vshcherbyna/igel#174]
Hello! Small request regarding Android compilations on Windows PC. Can you change the follow, in tt.cpp line 26 and 146 & uci.cpp line 48,  
`FROM "#if defined(__linux__)" TO "#if defined(__linux__) && !defined(__ANDROID__)"`
And remove from uci.cpp, line 63 and 109 the `"<< ARCHITECTURE"`
Thank you!

**Comment by vshcherbyna** [comment]
Thanks Alex for reporting this. It will be fixed in next Igel version. I will keep the ticket open meanwhile.

**Comment by vshcherbyna** [comment]
Fixed as of Igel 2.6.0 https://github.com/vshcherbyna/igel/releases/tag/2.6.0
