### ISSUE TITLE
Compiling errors in uci.cpp with g++ (msys2)

### ISSUE THREAD

**Issue by rwbc** [vshcherbyna/igel#178]
I see you removed the no popcount compilation for now?
Anyhow, when compiling my own version of it I get this decisive errors.

```
uci.cpp:333:5: error: expected unqualified-id before 'else'
  333 |     else if (name == "Ponder")
      |     ^~~~
uci.cpp:335:5: error: expected unqualified-id before 'else'
  335 |     else
      |     ^~~~
uci.cpp:337:1: error: expected declaration before '}' token
  337 | }
      | ^
```

**Comment by vshcherbyna** [comment]
Thanks rwbc,

I do not use this compiler in my tests, but will take a look to see what is wrong.

**Comment by ScallyBag** [comment]
Hi all,

I have fixed this and emailed Volodymyr 

Al.

**Comment by rwbc** [comment]
Thanks Al. Hopefully Volodymyr will add the fix soon.

**Comment by vshcherbyna** [comment]
Hello @rwbc ,

On a modern CPU with AVX2 support you can compile Igel with NNUE using the following command (from with-in src folder)
`
g++ -Wall -pthread -O3 -DEVAL_NNUE=1 -DUSE_AVX2=1 -DSYZYGY_SUPPORT=TRUE -march=native -flto *.cpp fathom/tbprobe.c nnue/*.cpp nnue/features/*.cpp -D_BTYPE=1 -DNDEBUG -o igel`

Please let me know if this works for you.

**Comment by rwbc** [comment]
> 
> 
> Hello @rwbc ,
> 
> On a modern CPU with AVX2 support you can compile Igel with NNUE using the following command (from with-in src folder)
> ` g++ -Wall -pthread -O3 -DEVAL_NNUE=1 -DUSE_AVX2=1 -DSYZYGY_SUPPORT=TRUE -march=native -flto *.cpp fathom/tbprobe.c nnue/*.cpp nnue/features/*.cpp -D_BTYPE=1 -DNDEBUG -o igel`
> 
> Please let me know if this works for you.

Of course I have no modern cpu, that's why I needed to compile even w/o popcount (core2).
In case you don't know rwbc = Guenther Simon (RWBC is my wellknown site) and I already
wrote in talkchess how I finally was able to compile for my hardware.
(even if there were quite some warnings...)

http://talkchess.com/forum3/viewtopic.php?f=2&t=67890&start=30#p857002

**Comment by vshcherbyna** [comment]
Ah, I see, I did not connect the dots that you are Guenther Simon, sorry :) Please let me know if there are still problems, until that time I will keep the ticket closed.
