### ISSUE TITLE
Android building issue.

### ISSUE THREAD

**Issue by AlexB123** [vshcherbyna/igel#183]
Hello. I was trying to compile Igel 2.8.0 for android, using NDK's Clang (cross compiler) on Windows and i got this errors (look at txt file). Some time ago, there was a similar problem when assembling Stockfish, which was solved. https://github.com/official-stockfish/Stockfish/issues/2860 
If you can please correct the code.
[errors.txt](https://github.com/vshcherbyna/igel/files/5274495/errors.txt)

**Comment by vshcherbyna** [comment]
@AlexB123 can you please try the fix on the branch bugfix_198, I would like to merge it once you confirm it fixes the issue.

**Comment by vshcherbyna** [comment]
Merged to master.
