### ISSUE TITLE
NNUE file for Igel ?

### ISSUE THREAD

**Issue by tissatussa** [vshcherbyna/igel#199]
I successfully compiled Igel 2.9.0 by downloading the ZIP package and doing 'make' in ./src .. this results in a binary of 215 Kb .. so i guess no NNUE file is compiled into this binary and i should get a proper NNUE file .. on the TalkChess forum i see that people mention the file "Igel_2_7_0.nnue" .. where can i download that file (or others) ?

**Comment by tryingsomestuff** [comment]
for igel2.9 you have this (https://github.com/vshcherbyna/igel/releases/download/2.9.0/ign-0-9b1937cc) inside the release assets.

**Comment by tissatussa** [comment]
I downloaded that net file but it doesn't work .. i use CuteChess to test engines .. in its config pane i left EvalFile blank, so Igel should load the default net file ./eval/nn.bin .. this works with other .bin files, but not with ign-0-9b1937cc .. i tried to rename the net file and change its path, but it still fails ..

looking into the CuteChess log gives another issue : the 'Skill' option gives a fatal error .. maybe it's not related to the net file issue .. here my config and the Engine Debug of CuteChess :

![Igel_2_9_0_fatal_error](https://user-images.githubusercontent.com/1109281/107119779-0eeb2880-688a-11eb-9753-1641ac47238b.png)

<Igel v2.9.0 NNUE 2(40): id name Igel 2.9.0 64 POPCNT
<Igel v2.9.0 NNUE 2(40): id author V. Medvedev, V. Shcherbyna
<Igel v2.9.0 NNUE 2(40): option name Hash type spin default 128 min 2 max 1048576
<Igel v2.9.0 NNUE 2(40): option name Threads type spin default 1 min 1 max 1024
<Igel v2.9.0 NNUE 2(40): option name Ponder type check default false
<Igel v2.9.0 NNUE 2(40): option name Skill Level type spin default 20 min 0 max 20
<Igel v2.9.0 NNUE 2(40): option name EvalFile type string default ./eval/nn.bin
<Igel v2.9.0 NNUE 2(40): uciok
>Igel v2.9.0 NNUE 2(40): setoption name EvalFile value 
>Igel v2.9.0 NNUE 2(40): setoption name Hash value 128
**>Igel v2.9.0 NNUE 2(40): setoption name Skill Level value 20**
>Igel v2.9.0 NNUE 2(40): setoption name Threads value 1
>Igel v2.9.0 NNUE 2(40): isready
**<Igel v2.9.0 NNUE 2(40): Fatal error: invalid parameters for setoption command**
<Igel v2.9.0 NNUE 2(40): Unknown option Skill
<Igel v2.9.0 NNUE 2(40): readyok

What's wrong ?

**Comment by vshcherbyna** [comment]
Hello  @tissatussa ,

Official releases of Igel have a network file already embedded in the binary, so you do not need to set it in the UI, therefore you need to remove option "EvalFile" in the UI.

In case the UI does not allow this, you can download a network file for a given release (for Igel 2.9.0 it is a file ign-0-9b1937cc in download section of the release https://github.com/vshcherbyna/igel/releases/tag/2.9.0) and set it manually.

**Comment by tissatussa** [comment]
I just solved the error myself : i DID have the wrong path for the net file ign-0-9b1937cc .. now Igel 2.9.0 runs OK .. i guess the Skill error was due to this .. nevermind.  Thanks for your help though ..

**Comment by vshcherbyna** [comment]
Glad to see it works for you @tissatussa . In next release of Igel I will make the validation for network file path a bit more user friendly to prevent issues like these.

**Comment by tissatussa** [comment]
OK, i want to let you know one more thing : in the CuteChess config pane an EvalFile value can be set by pasting a proper path/file .. but sometimes (!?) CuteChess has a small "[...]" button next to it to browse to the file .. this is convenient but that button is not present with all engines .. maybe you can adjust your code for it ..

**Comment by vshcherbyna** [comment]
Yes, in my next release of Igel these sort of issues will be gone.
