### ISSUE TITLE
i used this engine for a test as a lichess bot it's very slow 

### ISSUE THREAD

**Issue by ghost** [vshcherbyna/igel#201]
why ?? is it so slow?
but its good a very strong engine
am satisfied by the strength of the engine!

**Comment by vshcherbyna** [comment]
Slow compared to what?

**Comment by vshcherbyna** [comment]
Igel uses NNUE that can be slow on machines without avx-2 instructions, I will not be able to change this quickly.

**Comment by ghost** [comment]
Ok ,cannot it play fast? As I liked the engine very much

**Comment by vshcherbyna** [comment]
Define fast? What is the bench mark you are comparing Igel against?

**Comment by ghost** [comment]
What do you mean? , I did not get your point
