### ISSUE TITLE
Singular extension condition

### ISSUE THREAD

**Issue by ChizhovVadim** [vshcherbyna/igel#202]
When apply singular extension this condition:
hEntry.m_data.type == HASH_BETA
can be replaced with this:
hEntry.m_data.type == HASH_BETA || hEntry.m_data.type == HASH_EXACT

**Comment by vshcherbyna** [comment]
Thanks Vadim, running this change on open bench, so far it seems like a regression after 6356 games: http://chess.grantnet.us/test/10113/

**Comment by vshcherbyna** [comment]
STC passed,

```
ELO   | 2.72 +- 2.13 (95%)
SPRT  | 10.0+0.1s Threads=1 Hash=8MB
LLR   | 2.95 (-2.94, 2.94) [0.00, 5.00]
Games | N: 43598 W: 9486 L: 9145 D: 24967
```

Running LTC: http://chess.grantnet.us/test/10116/

**Comment by vshcherbyna** [comment]
LTC passed,

```
ELO   | 6.84 +- 4.25 (95%)
SPRT  | 60.0+0.6s Threads=1 Hash=64MB
LLR   | 2.95 (-2.94, 2.94) [0.00, 5.00]
Games | N: 7420 W: 1146 L: 1000 D: 5274
```

**Comment by vshcherbyna** [comment]
Thank you for reporting this improvement Vadim!
