### ISSUE TITLE
Patreon Link

### ISSUE THREAD

**Issue by g3rfx** [vshcherbyna/igel#252]
Hello,

The Patreon link leads to a page stating: “This patron isn’t supporting any creators at the moment”.

**Comment by vshcherbyna** [comment]
Hi @g3rfx ,

Thank you for your interest in donating to support Igel development. I added a PayPal donation link instead of Patreon to Igel home page (https://www.paypal.com/donate/?hosted_button_id=37NPEAY9XLRJE)
