### ISSUE TITLE
Igel 3.1.4 ARM64 (neon) .exe

### ISSUE THREAD

**Issue by microsmeta** [vshcherbyna/igel#257]
Hi!
I have managed to compile it for Mac M1 native and Windows 11 popcnt, but the second is a bit slow, yet already quite strong!
Could you please compile it also for Windows 11 ARM64 like 3.0.0 (or could you give me the modified makefile if you haven't an M1 right now) ?

Thank you in advance, Alex

**Comment by vshcherbyna** [comment]
Hi @microsmeta 

I will support ARM M1 eventually, but as of now due to lack of time I am trying to focus on supporting the mainstream hardware versions - PC with Intel/AMD cpus.
