### ISSUE TITLE
Cannot compile 3.1.5 with mingw 

### ISSUE THREAD

**Issue by microsmeta** [vshcherbyna/igel#259]
Hi!
Could you please compile the last 3.1.5 for Windows avx2 or bmi2 exe ?

I would like to add your last build to my all top engines gauntlet:
 https://banksiagui.com/forums/viewtopic.php?p=132&sid=63ebf715d1454c720147b87362efb991#p132

lto-wrapper.exe: warning: using serial compilation of 3 LTRANS jobs
lto-wrapper.exe: note: see the '-flto' option documentation for more information
C:\msys64\tmp\ccu0TuXu.s: Assembler messages:
C:\msys64\tmp\ccu0TuXu.s:8: Error: file not found: weights/ign-1-3e998e78
lto-wrapper.exe: fatal error: C:\msys64\mingw64\bin\g++.exe returned 1 exit status
compilation terminated.
C:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/12.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe
: error: lto-wrapper failed
collect2.exe: error: ld returned 1 exit status
make: *** [makefile:38: basic] Error 1

miniPC@DESKTOP-O7FHAH5 MINGW64 ~/igel-3.1.5/src

**Comment by vshcherbyna** [comment]
@microsmeta , well, the error message is exactly what the problem is: C:\msys64\tmp\ccu0TuXu.s:8: Error: file not found: weights/ign-1-3e998e78

In order to compile you need to specify the location of the weight file, one way is to create a folder weights in src and put there a file ign-1-3e998e78
